SRCS = main.cpp

FLAGS = $(FLAGS) /Iinclude
FLAGS = $(FLAGS) /I$(TSROOT)\plugins\platform\vulkan\extern

LDFLAGS = /subsystem:console lib\x64\SDL2main.lib lib\x64\SDL2.lib shell32.lib

include ..\..\Makefile.win.mk
