TESTS = \
	d3d11_device \
	d3d11_pipeline \
	d3d11_runtime \
	d3d11_swap_chain \
	d3d11_window \
	d3d12_device \
	d3d12_pipeline \
	d3d12_program \
	d3d12_runtime \
	d3d12_swap_chain \
	d3d12_texture \
	d3d12_window \
	d3d12_work_graph \
	d3d12_work_mesh \
	d3d12_work_query \
	d3d12_work_state \
	gl_device \
	gl_runtime \
	vk_device \
	vk_pipeline \
	vk_runtime \
	vk_spirv \
	vk_swap_chain

include ..\Makefile.win
