PLUGINS = \
	app \
	button \
	color \
	element \
	flow \
	imgui \
	manipulator \
	modal \
	plotter \
	popup \
	progress \
	slider \
	svg \
	tooltip

!if "$(VSVERSION)" == "170"
PLUGINS = $(PLUGINS) rmlui
!endif

include ..\Makefile.win
