plugins {
	id "com.android.application" version "8.3.1" apply true
}
android {
	namespace "com.tellusim.tsGraphicsSkinnedTracing"
	compileSdk 33
	defaultConfig {
		applicationId "com.tellusim.tsGraphicsSkinnedTracing"
		minSdk 33
		targetSdk 33
		versionCode 1
		versionName "1.0"
		ndk {
			abiFilters "arm64-v8a"
		}
	}
	externalNativeBuild {
		cmake {
			path "CMakeLists.txt"
		}
	}
}
copy {
	from files([ "../main.shader", "../model.glb", "../model.jpg", "../noise.jpg" ])
	into "src/main/assets"
}
copy {
	from "../../../../lib/android/arm64/libTellusim_arm64d.so"
	into "src/main/jniLibs/arm64-v8a"
}
