ifndef PLUGINS

PLUGINS = \
	binding \
	interface \
	parallel

endif

MAKE = make -f Makefile.ems
EXEC = $(TSROOT)/bin/ts_exec.sh

all:
	+@$(EXEC) -s "$(MAKE) -s -C @" $(PLUGINS)

install:
	+@$(EXEC) -s "$(MAKE) -s -C @ install" $(PLUGINS)

run:
	+@$(EXEC) -s "$(MAKE) -s -C @ run" $(PLUGINS)

clean:
	+@$(EXEC) -p "$(MAKE) -s -C @ clean" $(PLUGINS)

clear:
	+@$(EXEC) -s "$(MAKE) -s -C @ clear" $(PLUGINS)
