SRCS = main.cpp \
	source/TellusimXR.cpp \
	source/TellusimXRInput.cpp \
	source/TellusimXRWindow.cpp

FLAGS += -I$(TSROOT)/plugins/platform/vulkan/extern
FLAGS += -I$(TSROOT)/plugins/platform/opengles/extern
FLAGS += -I$(TSROOT)/plugins/platform/openxr/extern

include ../../Makefile.unx.mk
