SRCS = main.cpp \
	source/TellusimXR.cpp \
	source/TellusimXRInput.cpp \
	source/TellusimXRWindow.cpp

FLAGS = $(FLAGS) /I$(TSROOT)\plugins\platform\vulkan\extern
FLAGS = $(FLAGS) /I$(TSROOT)\plugins\platform\opengl\extern
FLAGS = $(FLAGS) /I$(TSROOT)\plugins\platform\openxr\extern

include ..\..\Makefile.win.mk
