TESTS = \
	alpha \
	atomic \
	blending \
	buffers \
	clipping \
	command \
	compute \
	device \
	dynamic \
	fence \
	formats \
	indirect \
	integer \
	matrix \
	multisample \
	precision \
	preprocessor \
	printf \
	reference \
	samplers \
	samples \
	stencil \
	storage \
	texture

include ../Makefile.ems
