SRCS = main.cpp \
	Plugins.cpp \
	source/TellusimControlFlow.cpp \
	source/TellusimControlFlowCPP.cpp \
	source/TellusimControlFlowGLSL.cpp \
	source/TellusimControlFlowMath.cpp

APK = tsInterfaceControlFlow

ASSETS = sansb.ttf

include ../../Makefile.and.mk
