SRCS = main.cpp \
	Plugins.cpp \
	source/TellusimControlFlow.cpp \
	source/TellusimControlFlowCPP.cpp \
	source/TellusimControlFlowGLSL.cpp \
	source/TellusimControlFlowMath.cpp

ASSETS = sansb.ttf

include ../../Makefile.ems.mk
