SRCS = main.cpp \
	Plugins.cpp \
	source/TellusimControlFlow.cpp \
	source/TellusimControlFlowCPP.cpp \
	source/TellusimControlFlowGLSL.cpp

IPA = tsInterfaceControlFlow

ASSETS = sansb.ttf

include ../../Makefile.ios.mk
